<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

<p>Hello my name is Rhendel Torrejos.</p>

<h3>Click Sample1 to see example CRUD generated by gii</h3>
<h3>Click Many-to-many example  to see many people with many interest :)</h3>




